// <auto-generated />
using System;
using AiConsultant.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiConsultant.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiConsultant.Core.Entities.BlogPost", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Content").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Slug").IsRequired().HasMaxLength(350).HasColumnType("character varying(350)");
                b.Property<string>("Tags").IsRequired().HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique();
                b.ToTable("BlogPosts");
            });

            modelBuilder.Entity("AiConsultant.Core.Entities.Consultation", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("Message").IsRequired().HasColumnType("text");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Organization").IsRequired().HasColumnType("text");
                b.Property<DateTime>("PreferredDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<string>("Type").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Consultations");
            });

            modelBuilder.Entity("AiConsultant.Core.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("AiConsultant.Core.Entities.Video", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<string>("YouTubeUrl").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Videos");
            });
#pragma warning restore 612, 618
        }
    }
}
